version: '3.1'

networks:
  vps_nginx-proxy:
    external: true

services:
  wp_wordpresstest_nginx:
    build: ./base
    image: wp_wordpresstest_nginx
    restart: always
    container_name: wp_wordpresstest_nginx
    volumes:
      - ../www:/var/www/html
    environment:
      - VIRTUAL_HOST=wordpresstest.com,www.wordpresstest.com
      - LETSENCRYPT_HOST=wordpresstest.com,www.wordpresstest.com
      - LETSENCRYPT_EMAIL=real.email@gmail.com
    expose:
      - "80"
    links:
      - wp_wordpresstest:wp_wordpresstest
    # Registra la vinculacion en /etc/hosts
    extra_hosts:
      - "docker-mysql.local:172.17.0.1"
    depends_on:
      - wp_wordpresstest
    networks:
      - vps_nginx-proxy

  wp_wordpresstest:
    image: wordpress:php7.4-fpm
    restart: always
    container_name: wp_wordpresstest
    volumes:
      - ./tmp:/tmp
      - ../www/public:/var/www/html # Wordpress carga todo los archivos como publicos
    env_file:
      - 'vars.env'
    expose:
      - "9000"
    # Registra la vinculacion en /etc/hosts
    # Lo siguiente se debe registrar en ./docker/vars.env
    extra_hosts:
      - "docker-mysql.local:172.17.0.1"
    networks:
      - vps_nginx-proxy